In [1]:
#Importo las librerías necesarias

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
import seaborn as sns
%matplotlib inline
from plotnine import *
import matplotlib.pyplot as plt

In [2]:
# Cargo los datasets elegidos para el análisis

internet = pd.read_excel("C:/Users/jugas/Proyecto_PIDA/dashboard-conectividad-ENACOM/data/internet.xlsx")
mapa_conectividad = pd.read_excel("C:/Users/jugas/Proyecto_PIDA/dashboard-conectividad-ENACOM/data/mapa_conectividad.xlsx")

Luego de una inspección visual en Excel, se determina que el archivo internet.xlsx consta de 15 páginas, y se dispone el despliegue por separado pero sólo de las páginas que contienen información relevante para nuestro estudio, que son:  
Hoja 3 "Accesos_tecnologia_localidad", Hoja 4 "Velocidad % por prov", Hoja 6 "Totales Accesos Por Tecnología", Hoja 8 "Penetración-poblacion", Hoja 9 "Penetracion-hogares", Hoja 10 "Penetracion-totales" Y Hoja 12"Accesos por velocidad".


In [3]:
internet_3 = pd.read_excel("C:/Users/jugas/Proyecto_PIDA/dashboard-conectividad-ENACOM/data/internet.xlsx", sheet_name="Accesos_tecnologia_localidad")
internet_4 = pd.read_excel("C:/Users/jugas/Proyecto_PIDA/dashboard-conectividad-ENACOM/data/internet.xlsx", sheet_name="Velocidad % por prov")
internet_6 = pd.read_excel("C:/Users/jugas/Proyecto_PIDA/dashboard-conectividad-ENACOM/data/internet.xlsx", sheet_name="Totales Accesos Por Tecnología")
internet_9 = pd.read_excel("C:/Users/jugas/Proyecto_PIDA/dashboard-conectividad-ENACOM/data/internet.xlsx", sheet_name="Penetracion-hogares")
internet_10 = pd.read_excel("C:/Users/jugas/Proyecto_PIDA/dashboard-conectividad-ENACOM/data/internet.xlsx", sheet_name="Penetracion-totales")
internet_12 = pd.read_excel("C:/Users/jugas/Proyecto_PIDA/dashboard-conectividad-ENACOM/data/internet.xlsx", sheet_name="Accesos por velocidad")


Inspección de nulos página por página

In [4]:
def calcular_porcentaje_nulos_total(df):
  """función para calcular el porcentaje total de nulos del df"""

  total_valores_nulos = df.isnull().sum().sum()
  total_valores = df.size
  porcentaje_nulos = (total_valores_nulos / total_valores) * 100
  return porcentaje_nulos

In [5]:
#Aplico la función para calcular el porcentaje en cada una de las hojas 

total_nulos_3 = calcular_porcentaje_nulos_total(internet_3)
print(total_nulos_3)

total_nulos_4 = calcular_porcentaje_nulos_total(internet_4)
print(total_nulos_4)

total_nulos_6 = calcular_porcentaje_nulos_total(internet_6)
print(total_nulos_6)

total_nulos_9 = calcular_porcentaje_nulos_total(internet_9)
print(total_nulos_9)

total_nulos_10 = calcular_porcentaje_nulos_total(internet_10)
print(total_nulos_10)

total_nulos_12 = calcular_porcentaje_nulos_total(internet_12)
print(total_nulos_12)

2.5702221406278687
0.0
0.0
0.0
0.0
0.05081300813008131


In [6]:
#Página 3 "Accesos_tecnologia_localidad"

internet_3.head()

Provincia     Partido               Localidad Link Indec  ADSL  \
0  BUENOS AIRES  25 de Mayo              25 de Mayo    6854100   755   
1  BUENOS AIRES  25 de Mayo               Del Valle    6854020   181   
2  BUENOS AIRES  25 de Mayo       Gobernador Ugarte    6854040     0   
3  BUENOS AIRES  25 de Mayo  Norberto de la Riestra    6854060     0   
4  BUENOS AIRES  25 de Mayo        Lucas Monteverde    6854050     0   

   CABLEMODEM  DIAL UP  FIBRA OPTICA  OTROS  SATELITAL  WIMAX  WIRELESS  \
0        4600        0             2      0        742      0       727   
1           0        0             0     10          1      0         0   
2           0        0             0      0          0      0       181   
3         782        0           496     16          0      0       185   
4           0        0             0      0          0      0         6   

   Total general  
0           6826  
1            192  
2            181  
3           1479  
4              6

In [7]:
print(internet_3.dtypes)

Provincia        object
Partido          object
Localidad        object
Link Indec       object
ADSL              int64
CABLEMODEM        int64
DIAL UP           int64
FIBRA OPTICA      int64
OTROS             int64
SATELITAL         int64
WIMAX             int64
WIRELESS          int64
Total general     int64
dtype: object


Eliminamos la columna Link Indec por considerarse irrelevante

In [8]:
internet_3 = internet_3.drop(['Link Indec', 'Total general'], axis=1)

Se verifica la cantidad de filas que corresponden a valores faltantes en cuanto a Provincia, Partido y Localidad, y se eliminan del dataset.

In [9]:
print("Número de filas antes de limpiar:", len(internet_3))
internet_3.dropna(subset=['Provincia'], inplace=True)
print("Número de filas después de limpiar:", len(internet_3))

Número de filas antes de limpiar: 3352
Número de filas después de limpiar: 3072


In [10]:
#Página 4 "Velocidad % por prov"

internet_4.head()

Año  Trimestre        Provincia  Mbps (Media de bajada)
0  2024          1     Buenos Aires                  159.13
1  2024          1  Capital Federal                  229.94
2  2024          1        Catamarca                   91.45
3  2024          1            Chaco                  107.51
4  2024          1           Chubut                   20.50

In [11]:
internet_4.isnull().sum()

Año                       0
Trimestre                 0
Provincia                 0
Mbps (Media de bajada)    0
dtype: int64

In [12]:
# Verificamos duplicados

print(internet_4.duplicated().sum())

0


In [13]:
internet_4.nunique()

Año                        11
Trimestre                   4
Provincia                  24
Mbps (Media de bajada)    978
dtype: int64

In [14]:
#Página 6 "Totales Accesos por tecnología"

internet_6.head()

Año  Trimestre     ADSL  Cablemodem  Fibra óptica  Wireless   Otros  \
0  2024          1   774475     5986957       4015101    598682  257941   
1  2023          4   836390     6022532       3908183    585760  194796   
2  2023          3   897895     6018832       3708718    581436  200027   
3  2023          2  1006509     5997149       3463988    581823  202428   
4  2023          1  1204417     6002582       3243411    576647  214838   

      Total        Periodo  
0  11633156   Ene-Mar 2024  
1  11547661   Oct-Dic 2023  
2  11406908  Jul-Sept 2023  
3  11251897   Abr-Jun 2023  
4  11241895   Ene-Mar 2023

In [15]:
internet_6.nunique()

Año             11
Trimestre        4
ADSL            41
Cablemodem      41
Fibra óptica    41
Wireless        41
Otros           41
Total           41
Periodo         41
dtype: int64

In [16]:
#Verifico los distintos valores contenidos en la columna "Año" y su dtype

internet_6['Año'].unique()

array([2024, 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014],
      dtype=int64)

In [17]:
internet_6['Trimestre'].unique()

array([1, 4, 3, 2], dtype=int64)

In [18]:
internet_9.head()

Año  Trimestre        Provincia  Accesos por cada 100 hogares
0  2024          1     Buenos Aires                         81.10
1  2024          1  Capital Federal                        119.53
2  2024          1        Catamarca                         68.82
3  2024          1            Chaco                         46.70
4  2024          1           Chubut                         84.89

In [19]:
internet_9.isnull().sum()

Año                             0
Trimestre                       0
Provincia                       0
Accesos por cada 100 hogares    0
dtype: int64

In [20]:
# Verificamos duplicados

print(internet_9.duplicated().sum())

0


In [21]:
internet_9.nunique()

Año                              11
Trimestre                         4
Provincia                        24
Accesos por cada 100 hogares    977
dtype: int64

In [22]:
internet_9.dtypes

Año                               int64
Trimestre                         int64
Provincia                        object
Accesos por cada 100 hogares    float64
dtype: object

In [23]:
internet_9['Año'].unique()

array([2024, 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014],
      dtype=int64)

In [24]:
internet_9['Trimestre'].unique()

array([1, 4, 3, 2], dtype=int64)

In [25]:
internet_10.head()

Año  Trimestre  Accesos por cada 100 hogares  Accesos por cada 100 hab  \
0  2024          1                         78.89                     24.79   
1  2023          4                         78.56                     24.66   
2  2023          3                         77.84                     24.41   
3  2023          2                         77.02                     24.14   
4  2023          1                         77.20                     24.17   

         Periodo  
0   Ene-Mar 2024  
1   Oct-Dic 2023  
2  Jul-Sept 2023  
3   Abr-Jun 2023  
4   Ene-Mar 2023

In [26]:
# Verificamos duplicados

print(internet_10.duplicated().sum())

0


In [27]:
#Verificamos tipos de datos

internet_10.dtypes

Año                               int64
Trimestre                         int64
Accesos por cada 100 hogares    float64
Accesos por cada 100 hab        float64
Periodo                          object
dtype: object

In [28]:
#Verificamos registros por columna

internet_10.nunique()

Año                             11
Trimestre                        4
Accesos por cada 100 hogares    41
Accesos por cada 100 hab        41
Periodo                         41
dtype: int64

In [29]:
#Verifico los distintos valores contenidos en la columna "Año" y su dtype

internet_10['Año'].unique()

array([2024, 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014],
      dtype=int64)

In [30]:
#Verifico los distintos valores contenidos en la columna "Trimestre" y su dtype

internet_10['Trimestre'].unique()

array([1, 4, 3, 2], dtype=int64)

In [31]:
#Página 12 "Accesos por velocidad"

internet_12.head()

Año  Trimestre        Provincia  HASTA 512 kbps  + 512 Kbps - 1 Mbps  \
0  2024          1     Buenos Aires         26002.0              22510.0   
1  2024          1  Capital Federal           516.0               5418.0   
2  2024          1        Catamarca            71.0                176.0   
3  2024          1            Chaco           236.0                416.0   
4  2024          1           Chubut           111.0               1083.0   

   + 1 Mbps - 6 Mbps  + 6 Mbps - 10 Mbps  + 10 Mbps - 20 Mbps  \
0           221185.0            233225.0             241778.0   
1            29753.0             51415.0              37369.0   
2             2872.0              3424.0               4204.0   
3            14156.0              9044.0               5533.0   
4            43828.0             31885.0              23024.0   

   + 20 Mbps - 30 Mbps  + 30 Mbps     OTROS      Total  
0             106418.0  4068292.0  125147.0  5044557.0  
1               5957.0  1374283.0       0.0  1504711.0  
2               1822.0    62294.0      70.0    74933.0  
3               5718.0   116624.0    3816.0   155543.0  
4              20261.0    33844.0   16640.0   170676.0

In [32]:
internet_12.isnull().sum()

Año                    0
Trimestre              0
Provincia              0
HASTA 512 kbps         0
+ 512 Kbps - 1 Mbps    0
+ 1 Mbps - 6 Mbps      0
+ 6 Mbps - 10 Mbps     0
+ 10 Mbps - 20 Mbps    0
+ 20 Mbps - 30 Mbps    0
+ 30 Mbps              0
OTROS                  6
Total                  0
dtype: int64

In [33]:
internet_12.nunique()

Año                     11
Trimestre                4
Provincia               24
HASTA 512 kbps         383
+ 512 Kbps - 1 Mbps    752
+ 1 Mbps - 6 Mbps      974
+ 6 Mbps - 10 Mbps     897
+ 10 Mbps - 20 Mbps    870
+ 20 Mbps - 30 Mbps    718
+ 30 Mbps              693
OTROS                  436
Total                  978
dtype: int64

In [34]:
print(internet_12.columns.tolist())

['Año', 'Trimestre', 'Provincia', 'HASTA 512 kbps', '+ 512 Kbps - 1 Mbps', '+ 1 Mbps - 6 Mbps', '+ 6 Mbps - 10 Mbps', '+ 10 Mbps - 20 Mbps', '+ 20 Mbps - 30 Mbps', '+ 30 Mbps', 'OTROS', 'Total']


In [35]:
#Verifico los distintos valores contenidos en la columna "Trimestre" y su dtype

internet_12['Trimestre'].unique()

array([1, 4, 3, 2], dtype=int64)

In [36]:
#Verifico los distintos valores contenidos en la columna "Año" y su dtype

internet_12['Año'].unique()

array([2024, 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014],
      dtype=int64)

In [37]:
# Verificamos duplicados

print(internet_12.duplicated().sum())

0


In [38]:
#Se eliminan columnas innecesarias

internet_12 = internet_12.drop('Total', axis=1)

Inspecciono el dataset complementario "mapa_conectividad"

In [39]:
mapa_conectividad.head()

Provincia     Partido          Localidad  Población ADSL Cablemódem  \
0  BUENOS AIRES  25 de Mayo         25 de Mayo      23408   SI         SI   
1  BUENOS AIRES  25 de Mayo    Agustín Mosconi        280   --         --   
2  BUENOS AIRES  25 de Mayo          Del Valle        899   SI         --   
3  BUENOS AIRES  25 de Mayo          Ernestina        145   SI         --   
4  BUENOS AIRES  25 de Mayo  Gobernador Ugarte        547   --         --   

  Dial Up Fibra óptica Satelital Wireless Telefonía Fija  3G  4G       Link  \
0      --           --        SI       SI             SI  SI  SI  6854100.0   
1      --           --        --       --             SI  --  --  6854010.0   
2      --           --        SI       --             --  SI  --  6854020.0   
3      --           --        --       --             SI  --  --  6854030.0   
4      --           --        --       SI             --  --  --  6854040.0   

     Latitud   Longitud  
0 -35.433939 -60.173121  
1 -35.739217 -60.559063  
2 -35.897345 -60.731609  
3 -35.270234 -59.557503  
4 -35.164397 -60.081358

In [40]:
mapa_conectividad.columns

Index(['Provincia', 'Partido', 'Localidad', 'Población', 'ADSL', 'Cablemódem',
       'Dial Up', 'Fibra óptica', 'Satelital', 'Wireless', 'Telefonía Fija',
       '3G', '4G', 'Link', 'Latitud', 'Longitud'],
      dtype='object')

In [41]:
mapa_conectividad.nunique()

Provincia           24
Partido            445
Localidad         3911
Población         2395
ADSL                 2
Cablemódem           2
Dial Up              2
Fibra óptica         2
Satelital            2
Wireless             2
Telefonía Fija       2
3G                   2
4G                   2
Link              3525
Latitud           4259
Longitud          4258
dtype: int64

In [42]:
# Convertimos "-" a NaN

mapa_conectividad = mapa_conectividad.replace("-", np.nan)

In [43]:
# Convertimos columnas de disponibilidad a booleano

bool_cols = ['ADSL', 'Cablemódem', 'Dial Up', 'Fibra óptica', 'Satelital', 'Wireless', 'Telefonía Fija', '3G', '4G']
mapa_conectividad[bool_cols] = mapa_conectividad[bool_cols].fillna(False).astype(bool)

In [44]:
# Buscmos y eliminamos duplicados

mapa_conectividad.drop_duplicates(inplace=True)

In [45]:
mapa_conectividad.describe()

Población          Link      Latitud     Longitud
count  4.305000e+03  4.293000e+03  4305.000000  4305.000000
mean   8.707207e+03  3.908916e+07   -32.263116   -63.039292
std    3.824490e+04  2.939911e+07     5.001839     3.829679
min    0.000000e+00  2.000010e+06   -77.874009   -72.891627
25%    1.170000e+02  1.009104e+07   -34.708542   -65.686443
50%    5.790000e+02  3.400705e+07   -32.286202   -63.450636
75%    3.217000e+03  6.612603e+07   -28.583403   -60.009923
max    1.317298e+06  9.401402e+07   -21.817293   -34.626560

In [46]:
#Se eliminan columnas innecesarias

mapa_conectividad = mapa_conectividad.drop('Link', axis=1)

Se exportan los df para su ingesta

In [58]:

internet_3.to_csv("C:/Users/jugas/Proyecto_PIDA/dashboard-conectividad-ENACOM/data/Accesos_tecnologia_localidad.csv", index=False)
internet_4.to_csv("C:/Users/jugas/Proyecto_PIDA/dashboard-conectividad-ENACOM/data/Velocidad % por prov.csv", index=False)
internet_6.to_csv("C:/Users/jugas/Proyecto_PIDA/dashboard-conectividad-ENACOM/data/Totales Accesos Por Tecnología.csv", index=False)
internet_9.to_csv("C:/Users/jugas/Proyecto_PIDA/dashboard-conectividad-ENACOM/data/Penetracion-hogares.csv", index=False)
internet_10.to_csv("C:/Users/jugas/Proyecto_PIDA/dashboard-conectividad-ENACOM/data/Penetracion_totales.csv", index=False)
internet_12.to_csv("C:/Users/jugas/Proyecto_PIDA/dashboard-conectividad-ENACOM/data/Accesos por velocidad.csv", index=False)
mapa_conectividad.to_csv("C:/Users/jugas/Proyecto_PIDA/dashboard-conectividad-ENACOM/data/mapa_conectividad.csv", index=False)